### PR TITLE
Spark 4 - fix context facetory

### LINKED ISSUE #3931: [BUG] io.openlineage.spark.agent.lifecycle.ContextFactory compatibility with Spark 4
### OpenLineage integration/client

Spark integration

### OpenLineage version

Java dependency for Spark 4:

io.openlineage
openlineage-spark_2.13
1.36.0

### Technology and package versions

Spark 4.0.0 built from source - https://github.com/apache/spark/tree/v4.0.0
Scala 2.13.8
openjdk 17.0.15
Python 3.10.15

### Environment configuration

_No response_

### Deployment details

_No response_

### Problem details

Another issue I came across while trying to use with Spark 4, [here](https://github.com/OpenLineage/OpenLineage/blob/c0d5a74f226dff35bb35e6dcfda97d33232b5e49/integration/spark/app/src/main/java/io/openlineage/spark/agent/lifecycle/ContextFactory.java#L24) the import is incompatible with Spark 4.

```
        ERROR Utils: uncaught error in thread spark-listener-group-shared, stopping SparkContext
        java.lang.NoSuchMethodError: 'org.apache.spark.sql.SparkSession org.apache.spark.sql.execution.QueryExecution.sparkSession()'
        	at io.openlineage.spark.agent.lifecycle.ContextFactory.createSparkSQLExecutionContext(ContextFactory.java:95)
        	at io.openlineage.spark.agent.OpenLineageSparkListener.lambda$getSparkSQLExecutionContext$16(OpenLineageSparkListener.java:281)
        	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        	at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2760)
        	at io.openlineage.spark.agent.OpenLineageSparkListener.getSparkSQLExecutionContext(OpenLineageSparkListener.java:279)
        	at io.openlineage.spark.agent.OpenLineageSparkListener.sparkSQLExecStart(OpenLineageSparkListener.java:137)
        	at io.openlineage.spark.agent.OpenLineageSparkListener.onOtherEvent(OpenLineageSparkListener.java:127)
        	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:100)
        	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
        	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:38)
        	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:38)
        	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:118)
        	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:102)
        	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:106)
        	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:106)
        	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.scala:17)
        	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:101)
        	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:97)
        	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1279)
        	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:97)
```

### What you think should happen instead

_No response_

### How to reproduce

Can't reproduce outside my environment

### Additional details

_No response_

### Do you plan to make this contribution yourself?

- [ ] I am interested in doing this work

### PR DESCRIPTION
**Pull request by pawel-big-lebowski**
Closes  #3931

### CODE REVIEW

File: integration/spark/app/src/main/java/io/openlineage/spark/agent/lifecycle/ContextFactory.java [hunk 1]
```diff
@@ -92,7 +92,7 @@ public Optional<ExecutionContext> createSparkSQLExecutionContext(long executionI
       log.error("Query execution is null: can't emit event for executionId {}", executionId);
       return Optional.empty();
     }
-    SparkSession sparkSession = queryExecution.sparkSession();
+    SparkSession sparkSession = Spark4CompatUtils.getSparkSession(queryExecution);
```
Comment (romangershgorin) [inline integration/spark/app/src/main/java/io/openlineage/spark/agent/lifecycle/ContextFactory.java:96]: might be a stupid question, having very limited knowledge in Java, but how does it work without import of Spark4CompatUtils? I tried to build locally with this commit, but getting `error: cannot find symbol`. (using commands ./buildDependencies.sh && ./gradlew publishToMavenLocal -Pscala.binary.version=2.13 to build required jar). Though importing like this `import io.openlineage.spark.agent.Spark4CompatUtils;` did not work for me also, still can't find symbol. Maybe something missing in gradle config?
Another question, is that correct that Utils are defined as part of tests, but used in main source code here?
OpenLineage/integration/spark/app/src/**test**/java/io/openlineage/spark/agent/Spark4CompatUtils.java
OpenLineage/integration/spark/app/src/**main**/java/io/openlineage/spark/agent/lifecycle/ContextFactory.java
Does it work like this?

Comment (romangershgorin) [reply integration/spark/app/src/main/java/io/openlineage/spark/agent/lifecycle/ContextFactory.java:96]: @pawel-big-lebowski I tried to move the whole Spark4CompatUtils file to src instead of tests and it helped to build both code and tests, would that be a good way to fix build? I can commit such change here if you agree with it

**Review by romangershgorin — APPROVED** [review]

**Review by ddebowczyk92 — APPROVED** [review]
